config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#buscar"
  get "/buscar/(:busca)/:page", to: "application#buscar", as: "busca"
  get "/buscar/:page", to: "application#buscar", as: "busca_inicial"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/imagem.rb
class Imagem < ApplicationRecord
	belongs_to :usuario
	validates :nome, uniqueness: :true
	before_create :escolhe_nome
	after_create :cria_arquivo
	after_destroy :deleta_arquivo

	def escolhe_nome
		self.nome = "#{self.nome.split('.').first}_#{SecureRandom.hex(20)}_.#{self.nome.split('.').last}"
		escolhe_nome if Imagem.where(nome: self.nome).any?
	end

	def cria_arquivo
		arquivo = File.open(file_path,'wb')
		arquivo.write(self.arquivo)
		arquivo.close
	end

	def path
		file_path.gsub('public','')
	end

	def deleta_arquivo
		File.delete(file_path) if File.exist?(file_path)
	end

	def file_path
		"public/images/#{self.nome}"
	end

end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_many :imagens
	after_destroy :deleta_imagens

	def thumb_image
		self.imagens.filter{|img| img.nome.match?(/.*_thumb_.*/) }.first
	end

	def medium_image
		self.imagens.filter{|img| img.nome.match?(/.*_thumb_.*/) }.first
	end

	def large_image
		self.imagens.filter{|img| img.nome.match?(/.*_thumb_.*/) }.first
	end

	def deleta_imagens
		self.imagens.each{|img| img.destroy }
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def buscar
		params[:page] ||= 1
		if params[:busca].present?
			string_busca = params[:busca].upcase.gsub(/\s+/,'.*').gsub(/([*.?<>+{}\[\]\^\$\\])/,'|\1').gsub('|','\\')
			@usuarios = Usuario.all.filter{|usuario| I18n.transliterate(usuario.nome.upcase).match?(Regexp.new(".*#{string_busca}.*"))}
			@usuarios = Usuario.where(id: @usuarios.pluck(:id)).page(params[:page]).per(10)
		else
			@usuarios = Usuario.all.page(params[:page]).per(10)
		end
		@total_pages = @usuarios.total_pages
		@total_resultados = @usuarios.total_count
		@page = params[:page].to_i
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/buscar.html.erb
<div id="container">
	<div id="left">
	</div>
	<div id="center">
			<form id="form-busca" method="GET" action="<%= busca_inicial_path(page: 1) %>"hidden></form>
			<div class="grupo-busca">
				<input class="input-busca" form="form-busca" type="text" name="busca" placeholder="Digite o nome do usuário..." value="<%= params[:busca] %>">
				<button class="botao-busca" form="form-busca" type="submit">Buscar</button>
			</div>
			<p class="total-results"><%= @total_resultados.present? ? @total_resultados : @usuarios.count %> usuarios encontrados</p>
			<% if @usuarios.present? %>
				<div id="lista-resultados">
					<% @usuarios.each do |usuario| %>
						<div class="resultado-card">
							<div class="card-imagem-container">
								<img src="<%= usuario.large_image.present? ? usuario.large_image.path : 'https://dummyimage.com/48x48/000/fff' %>" class="card-imagem">
							</div>
							<div class="card-body">
								<div class="card-body-title"><%= usuario.nome %></div>
								<div class="card-body-subtitle"><%= usuario.email %></div>
								<div class="card-body-tag-<%= usuario.genero %>"><%= usuario.genero.capitalize %></div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
			<% if @page.present? %>
				<div id="page-navigator">
					<% if @page % 4 == 0%>
						<a id="previous-page" href="<%= busca_path(busca: params[:busca],page: @page > 1 ? @page-1 : @page) %>" <%= @page == 1 ? 'disabled' : '' %>>Anterior</a>
						<% ((@page-3)..@page).each do |page| %>
							<% if page <= @total_pages %>
								<a class="filling<%= page == @page ? "-active" : "" %>" href="<%= busca_path(busca: params[:busca],page: page) %>"><%= page %></button>
							<% end %>
						<% end %>
						<a id="next-page" href="<%= busca_path(busca: params[:busca],page: @page+1 <= @total_pages ? @page+1 : @page) %>" <%= @page == @total_pages ? 'disabled' : '' %>>Próximo</a>
					<% else %>
						<a id="previous-page" href="<%= busca_path(busca: params[:busca],page: @page > 1 ? @page-1 : @page) %>" <%= @page == 1 ? 'disabled' : '' %>>Anterior</a>
						<% ((@page-3)+(4-@page % 4)..@page+(4-@page % 4)).each do |page| %>
							<% if page <= @total_pages %>
								<a class="filling<%= page == @page ? "-active" : "" %>" href="<%= busca_path(busca: params[:busca],page: page) %>"><%= page %></button>
							<% end %>
						<% end %>
						<a id="next-page" href="<%= busca_path(busca: params[:busca],page: @page+1 <= @total_pages ? @page+1 : @page) %>" <%= @page == @total_pages ? 'disabled' : '' %>>Próximo</a>
					<% end %>
				</div>
			<% end %>
	</div>
	<div id="right">
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConsultaUsuarios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>